stages:
  - lint

cache:
  paths:
    - node_modules/

eslint:
  stage: lint
  image: node:20-alpine
  before_script:
    - npm ci
  script: |
    set +euo pipefail  # don't abort if any following command fails
    npm run lint:js -- --format=junit --output-file=logs/eslint-junit.xml
    npm run lint:js -- --format gitlab
  artifacts:
    paths:
      - logs/eslint-junit.xml
      - gl-codequality.json
    reports:
      junit: logs/eslint-junit.xml
      codequality: gl-codequality.json
