stages:
  - lint

cache:
  paths:
    - node_modules/

eslint:
  stage: lint
  image: node:20-alpine
  before_script:
    - npm ci
  script: |
    npm run lint:js -- --format=junit --output-file=logs/eslint-junit.xml
  artifacts:
    paths:
      - logs/eslint-junit.xml
    reports:
      junit: logs/eslint-junit.xml
